export const countryCodes = [
  { countryCode: "BRA", country: "Brasil", code: "+55" },
  { countryCode: "AFG", country: "Afeganistão", code: "+93" },
  { countryCode: "ALB", country: "Albânia", code: "+355" },
  { countryCode: "DZA", country: "Argélia", code: "+213" },
  { countryCode: "ASM", country: "Samoa Americana", code: "+1" },
  { countryCode: "AND", country: "Andorra", code: "+376" },
  { countryCode: "AGO", country: "Angola", code: "+244" },
  { countryCode: "AIA", country: "Anguila", code: "+1" },
  { countryCode: "ATA", country: "Antártica", code: "+672" },
  { countryCode: "ATG", country: "Antígua e Barbuda", code: "+1" },
  { countryCode: "ARG", country: "Argentina", code: "+54" },
  { countryCode: "ARM", country: "Armênia", code: "+374" },
  { countryCode: "ABW", country: "Aruba", code: "+297" },
  { countryCode: "AUS", country: "Austrália", code: "+61" },
  { countryCode: "AUT", country: "Áustria", code: "+43" },
  { countryCode: "AZE", country: "Azerbaijão", code: "+994" },
  { countryCode: "BHS", country: "Bahamas", code: "+1" },
  { countryCode: "BHR", country: "Bahrein", code: "+973" },
  { countryCode: "BGD", country: "Bangladesh", code: "+880" },
  { countryCode: "BRB", country: "Barbados", code: "+1" },
  { countryCode: "BLR", country: "Belarus", code: "+375" },
  { countryCode: "BEL", country: "Bélgica", code: "+32" },
  { countryCode: "BLZ", country: "Belize", code: "+501" },
  { countryCode: "BEN", country: "Benin", code: "+229" },
  { countryCode: "BMU", country: "Bermudas", code: "+1" },
  { countryCode: "BTN", country: "Butão", code: "+975" },
  { countryCode: "BOL", country: "Bolívia", code: "+591" },
  { countryCode: "BIH", country: "Bósnia e Herzegovina", code: "+387" },
  { countryCode: "BWA", country: "Botsuana", code: "+267" },
  { countryCode: "BRN", country: "Brunei", code: "+673" },
  { countryCode: "BGR", country: "Bulgária", code: "+359" },
  { countryCode: "BFA", country: "Burkina Faso", code: "+226" },
  { countryCode: "BDI", country: "Burundi", code: "+257" },
  { countryCode: "KHM", country: "Camboja", code: "+855" },
  { countryCode: "CMR", country: "Camarões", code: "+237" },
  { countryCode: "CAN", country: "Canadá", code: "+1" },
  { countryCode: "CPV", country: "Cabo Verde", code: "+238" },
  { countryCode: "CYM", country: "Ilhas Cayman", code: "+1" },
  { countryCode: "CAF", country: "República Centro-Africana", code: "+236" },
  { countryCode: "TCD", country: "Chade", code: "+235" },
  { countryCode: "CHL", country: "Chile", code: "+56" },
  { countryCode: "CHN", country: "China", code: "+86" },
  { countryCode: "COL", country: "Colômbia", code: "+57" },
  { countryCode: "COM", country: "Comores", code: "+269" },
  { countryCode: "COG", country: "Congo", code: "+242" },
  { countryCode: "COD", country: "Congo, República Democrática", code: "+243" },
  { countryCode: "CRI", country: "Costa Rica", code: "+506" },
  { countryCode: "CIV", country: "Costa do Marfim", code: "+225" },
  { countryCode: "HRV", country: "Croácia", code: "+385" },
  { countryCode: "CUB", country: "Cuba", code: "+53" },
  { countryCode: "CYP", country: "Chipre", code: "+357" },
  { countryCode: "CZE", country: "República Tcheca", code: "+420" },
  { countryCode: "DNK", country: "Dinamarca", code: "+45" },
  { countryCode: "DJI", country: "Djibuti", code: "+253" },
  { countryCode: "DMA", country: "Dominica", code: "+1" },
  { countryCode: "DOM", country: "República Dominicana", code: "+1" },
  { countryCode: "ECU", country: "Equador", code: "+593" },
  { countryCode: "EGY", country: "Egito", code: "+20" },
  { countryCode: "SLV", country: "El Salvador", code: "+503" },
  { countryCode: "GNQ", country: "Guiné Equatorial", code: "+240" },
  { countryCode: "ERI", country: "Eritreia", code: "+291" },
  { countryCode: "EST", country: "Estônia", code: "+372" },
  { countryCode: "SWZ", country: "Essuatíni", code: "+268" },
  { countryCode: "ETH", country: "Etiópia", code: "+251" },
  { countryCode: "FIN", country: "Finlândia", code: "+358" },
  { countryCode: "FRA", country: "França", code: "+33" },
  { countryCode: "GAB", country: "Gabão", code: "+241" },
  { countryCode: "GMB", country: "Gâmbia", code: "+220" },
  { countryCode: "GEO", country: "Geórgia", code: "+995" },
  { countryCode: "DEU", country: "Alemanha", code: "+49" },
  { countryCode: "GHA", country: "Gana", code: "+233" },
  { countryCode: "GRC", country: "Grécia", code: "+30" },
  { countryCode: "GRD", country: "Granada", code: "+1" },
  { countryCode: "GTM", country: "Guatemala", code: "+502" },
  { countryCode: "GIN", country: "Guiné", code: "+224" },
  { countryCode: "GNB", country: "Guiné-Bissau", code: "+245" },
  { countryCode: "GUY", country: "Guiana", code: "+592" },
  { countryCode: "HTI", country: "Haiti", code: "+509" },
  { countryCode: "HND", country: "Honduras", code: "+504" },
  { countryCode: "HUN", country: "Hungria", code: "+36" },
  { countryCode: "ISL", country: "Islândia", code: "+354" },
  { countryCode: "IND", country: "Índia", code: "+91" },
  { countryCode: "IDN", country: "Indonésia", code: "+62" },
  { countryCode: "IRN", country: "Irã", code: "+98" },
  { countryCode: "IRQ", country: "Iraque", code: "+964" },
  { countryCode: "IRL", country: "Irlanda", code: "+353" },
  { countryCode: "ISR", country: "Israel", code: "+972" },
  { countryCode: "ITA", country: "Itália", code: "+39" },
  { countryCode: "JPN", country: "Japão", code: "+81" },
  { countryCode: "JOR", country: "Jordânia", code: "+962" },
  { countryCode: "KAZ", country: "Cazaquistão", code: "+7" },
  { countryCode: "KEN", country: "Quênia", code: "+254" },
  { countryCode: "KWT", country: "Kuwait", code: "+965" },
  { countryCode: "KGZ", country: "Quirguistão", code: "+996" },
  { countryCode: "LAO", country: "Laos", code: "+856" },
  { countryCode: "LVA", country: "Letônia", code: "+371" },
  { countryCode: "LBN", country: "Líbano", code: "+961" },
  { countryCode: "LSO", country: "Lesoto", code: "+266" },
  { countryCode: "LBR", country: "Libéria", code: "+231" },
  { countryCode: "LBY", country: "Líbia", code: "+218" },
  { countryCode: "LIE", country: "Liechtenstein", code: "+423" },
  { countryCode: "LTU", country: "Lituânia", code: "+370" },
  { countryCode: "LUX", country: "Luxemburgo", code: "+352" },
  { countryCode: "MDG", country: "Madagascar", code: "+261" },
  { countryCode: "MWI", country: "Malawi", code: "+265" },
  { countryCode: "MYS", country: "Malásia", code: "+60" },
  { countryCode: "MDV", country: "Maldivas", code: "+960" },
  { countryCode: "MLI", country: "Mali", code: "+223" },
  { countryCode: "MLT", country: "Malta", code: "+356" },
  { countryCode: "MRT", country: "Mauritânia", code: "+222" },
  { countryCode: "MUS", country: "Maurício", code: "+230" },
  { countryCode: "MEX", country: "México", code: "+52" },
  { countryCode: "MDA", country: "Moldávia", code: "+373" },
  { countryCode: "MCO", country: "Mônaco", code: "+377" },
  { countryCode: "MNG", country: "Mongólia", code: "+976" }
]


