export const listCountries = [
  { code: "AFG", name: "Afeganistão" },
  { code: "ALB", name: "Albânia" },
  { code: "DZA", name: "Argélia" },
  { code: "AND", name: "Andorra" },
  { code: "AGO", name: "Angola" },
  { code: "ARG", name: "Argentina" },
  { code: "ARM", name: "Armênia" },
  { code: "AUS", name: "Austrália" },
  { code: "AUT", name: "Áustria" },
  { code: "AZE", name: "Azerbaijão" },
  { code: "BHS", name: "Bahamas" },
  { code: "BGD", name: "Bangladesh" },
  { code: "BLR", name: "Belarus" },
  { code: "BEL", name: "Bélgica" },
  { code: "BOL", name: "Bolívia" },
  { code: "BIH", name: "Bósnia e Herzegovina" },
  { code: "BWA", name: "Botswana" },
  { code: "BRA", name: "Brasil" },
  { code: "BGR", name: "Bulgária" },
  { code: "CAN", name: "Canadá" },
  { code: "CHL", name: "Chile" },
  { code: "CHN", name: "China" },
  { code: "COL", name: "Colômbia" },
  { code: "CRI", name: "Costa Rica" },
  { code: "HRV", name: "Croácia" },
  { code: "CUB", name: "Cuba" },
  { code: "CYP", name: "Chipre" },
  { code: "CZE", name: "Tchéquia" },
  { code: "DNK", name: "Dinamarca" },
  { code: "DOM", name: "República Dominicana" },
  { code: "ECU", name: "Equador" },
  { code: "EGY", name: "Egito" },
  { code: "SLV", name: "El Salvador" },
  { code: "EST", name: "Estônia" },
  { code: "ETH", name: "Etiópia" },
  { code: "FIN", name: "Finlândia" },
  { code: "FRA", name: "França" },
  { code: "GEO", name: "Geórgia" },
  { code: "DEU", name: "Alemanha" },
  { code: "GHA", name: "Gana" },
  { code: "GRC", name: "Grécia" },
  { code: "GTM", name: "Guatemala" },
  { code: "HTI", name: "Haiti" },
  { code: "HND", name: "Honduras" },
  { code: "HUN", name: "Hungria" },
  { code: "ISL", name: "Islândia" },
  { code: "IND", name: "Índia" },
  { code: "IDN", name: "Indonésia" },
  { code: "IRN", name: "Irã" },
  { code: "IRQ", name: "Iraque" },
  { code: "IRL", name: "Irlanda" },
  { code: "ISR", name: "Israel" },
  { code: "ITA", name: "Itália" },
  { code: "JAM", name: "Jamaica" },
  { code: "JPN", name: "Japão" },
  { code: "JOR", name: "Jordânia" },
  { code: "KAZ", name: "Cazaquistão" },
  { code: "KEN", name: "Quênia" },
  { code: "KOR", name: "Coreia do Sul" },
  { code: "KWT", name: "Kuwait" },
  { code: "LVA", name: "Letônia" },
  { code: "LBN", name: "Líbano" },
  { code: "LBY", name: "Líbia" },
  { code: "LTU", name: "Lituânia" },
  { code: "LUX", name: "Luxemburgo" },
  { code: "MDG", name: "Madagáscar" },
  { code: "MYS", name: "Malásia" },
  { code: "MEX", name: "México" },
  { code: "MAR", name: "Marrocos" },
  { code: "MOZ", name: "Moçambique" },
  { code: "NLD", name: "Países Baixos" },
  { code: "NZL", name: "Nova Zelândia" },
  { code: "NIC", name: "Nicarágua" },
  { code: "NGA", name: "Nigéria" },
  { code: "NOR", name: "Noruega" },
  { code: "PAK", name: "Paquistão" },
  { code: "PAN", name: "Panamá" },
  { code: "PRY", name: "Paraguai" },
  { code: "PER", name: "Peru" },
  { code: "PHL", name: "Filipinas" },
  { code: "POL", name: "Polônia" },
  { code: "PRT", name: "Portugal" },
  { code: "ROU", name: "Romênia" },
  { code: "RUS", name: "Rússia" },
  { code: "SAU", name: "Arábia Saudita" },
  { code: "SRB", name: "Sérvia" },
  { code: "SGP", name: "Singapura" },
  { code: "SVK", name: "Eslováquia" },
  { code: "SVN", name: "Eslovênia" },
  { code: "ZAF", name: "África do Sul" },
  { code: "ESP", name: "Espanha" },
  { code: "SWE", name: "Suécia" },
  { code: "CHE", name: "Suíça" },
  { code: "SYR", name: "Síria" },
  { code: "TWN", name: "Taiwan" },
  { code: "THA", name: "Tailândia" },
  { code: "TUR", name: "Turquia" },
  { code: "UKR", name: "Ucrânia" },
  { code: "ARE", name: "Emirados Árabes Unidos" },
  { code: "GBR", name: "Reino Unido" },
  { code: "USA", name: "Estados Unidos" },
  { code: "URY", name: "Uruguai" },
  { code: "UZB", name: "Uzbequistão" },
  { code: "VEN", name: "Venezuela" },
  { code: "VNM", name: "Vietnã" },
  { code: "YEM", name: "Iêmen" },
  { code: "ZMB", name: "Zâmbia" },
  { code: "ZWE", name: "Zimbábue" },
];
