export const listCountries = [
  { id: 2, name: "Afeganistão" },
  { id: 3, name: "África do Sul" },
  { id: 4, name: "Albânia" },
  { id: 5, name: "Alemanha" },
  { id: 6, name: "Andorra" },
  { id: 7, name: "Angola" },
  { id: 8, name: "Antígua e Barbuda" },
  { id: 9, name: "Arábia Saudita" },
  { id: 10, name: "Argélia" },
  { id: 11, name: "Argentina" },
  { id: 12, name: "Armênia" },
  { id: 13, name: "Austrália" },
  { id: 14, name: "Áustria" },
  { id: 15, name: "Azerbaijão" },
  { id: 16, name: "Bahamas" },
  { id: 17, name: "Bahrein" },
  { id: 18, name: "Bangladesh" },
  { id: 19, name: "Barbados" },
  { id: 20, name: "Bélgica" },
  { id: 21, name: "Belize" },
  { id: 22, name: "Benim" },
  { id: 23, name: "Bielorrússia" },
  { id: 24, name: "Bolívia" },
  { id: 25, name: "Bósnia e Herzegovina" },
  { id: 26, name: "Botsuana" },
  { id: 27, name: "Brasil" },
  { id: 28, name: "Brunei" },
  { id: 29, name: "Bulgária" },
  { id: 30, name: "Burquina Fasso" },
  { id: 31, name: "Burundi" },
  { id: 32, name: "Butão" },
  { id: 33, name: "Cabo Verde" },
  { id: 34, name: "Camarões" },
  { id: 35, name: "Camboja" },
  { id: 36, name: "Canadá" },
  { id: 37, name: "Catar" },
  { id: 38, name: "Cazaquistão" },
  { id: 39, name: "Chade" },
  { id: 40, name: "Chile" },
  { id: 41, name: "China" },
  { id: 42, name: "Chipre" },
  { id: 43, name: "Colômbia" },
  { id: 44, name: "Comores" },
  { id: 45, name: "Congo (Brazzaville)" },
  { id: 46, name: "Congo (Kinshasa)" },
  { id: 47, name: "Coreia do Norte" },
  { id: 48, name: "Coreia do Sul" },
  { id: 49, name: "Costa do Marfim" },
  { id: 50, name: "Costa Rica" },
  { id: 51, name: "Croácia" },
  { id: 52, name: "Cuba" },
  { id: 53, name: "Curacao" },
  { id: 54, name: "Dinamarca" },
  { id: 55, name: "Djibuti" },
  { id: 56, name: "Dominica" },
  { id: 57, name: "Egito" },
  { id: 58, name: "El Salvador" },
  { id: 59, name: "Emirados Árabes Unidos" },
  { id: 60, name: "Equador" },
  { id: 61, name: "Eritreia" },
  { id: 62, name: "Eslováquia" },
  { id: 63, name: "Eslovênia" },
  { id: 64, name: "Espanha" },
  { id: 65, name: "Estados Unidos" },
  { id: 66, name: "Estônia" },
  { id: 67, name: "Eswatini" },
  { id: 68, name: "Etiópia" },
  { id: 69, name: "Fiji" },
  { id: 70, name: "Filipinas" },
  { id: 71, name: "Finlândia" },
  { id: 72, name: "França" },
  { id: 73, name: "Gabão" },
  { id: 74, name: "Gâmbia" },
  { id: 75, name: "Gana" },
  { id: 76, name: "Geórgia" },
  { id: 77, name: "Granada" },
  { id: 78, name: "Grécia" },
  { id: 79, name: "Guatemala" },
  { id: 80, name: "Guiana" },
  { id: 81, name: "Guiné" },
  { id: 82, name: "Guiné-Bissau" },
  { id: 83, name: "Guiné Equatorial" },
  { id: 84, name: "Haiti" },
  { id: 85, name: "Holanda" },
  { id: 86, name: "Honduras" },
  { id: 87, name: "Hungria" },
  { id: 88, name: "Iêmen" },
  { id: 89, name: "Ilhas Cook" },
  { id: 90, name: "Ilhas Marshall" },
  { id: 91, name: "Ilhas Salomão" },
  { id: 92, name: "Índia" },
  { id: 93, name: "Indonésia" },
  { id: 94, name: "Irã" },
  { id: 95, name: "Iraque" },
  { id: 96, name: "Irlanda" },
  { id: 97, name: "Islândia" },
  { id: 98, name: "Israel" },
  { id: 99, name: "Itália" },
  { id: 100, name: "Jamaica" },
  { id: 101, name: "Japão" },
  { id: 102, name: "Jordânia" },
  { id: 103, name: "Kiribati" },
  { id: 104, name: "Kosovo" },
  { id: 105, name: "Kuwait" },
  { id: 106, name: "Laos" },
  { id: 107, name: "Lesoto" },
  { id: 108, name: "Letônia" },
  { id: 109, name: "Líbano" },
  { id: 110, name: "Libéria" },
  { id: 111, name: "Líbia" },
  { id: 112, name: "Liechtenstein" },
  { id: 113, name: "Lituânia" },
  { id: 114, name: "Luxemburgo" },
  { id: 115, name: "Madagascar" },
  { id: 116, name: "Malásia" },
  { id: 117, name: "Malávi" },
  { id: 118, name: "Maldivas" },
  { id: 119, name: "Mali" },
  { id: 120, name: "Malta" },
  { id: 121, name: "Marrocos" },
  { id: 122, name: "Maurícia" },
  { id: 123, name: "Mauritânia" },
  { id: 124, name: "México" },
  { id: 125, name: "Micronésia" },
  { id: 126, name: "Moçambique" },
  { id: 127, name: "Moldávia" },
  { id: 128, name: "Mônaco" },
  { id: 129, name: "Mongólia" },
  { id: 130, name: "Montenegro" },
  { id: 131, name: "Myanmar (Birmânia)" },
  { id: 132, name: "Namíbia" },
  { id: 133, name: "Nauru" },
  { id: 134, name: "Nepal" },
  { id: 135, name: "Nicarágua" },
  { id: 136, name: "Níger" },
  { id: 137, name: "Nigéria" },
  { id: 138, name: "Noruega" },
  { id: 139, name: "Nova Zelândia" },
  { id: 140, name: "Omã" },
  { id: 141, name: "Países Baixos" },
  { id: 142, name: "Palau" },
  { id: 143, name: "Panamá" },
  { id: 144, name: "Papua-Nova Guiné" },
  { id: 145, name: "Paquistão" },
  { id: 146, name: "Paraguai" },
  { id: 147, name: "Peru" },
  { id: 148, name: "Polônia" },
  { id: 149, name: "Portugal" },
  { id: 150, name: "Quênia" },
  { id: 151, name: "Quirguistão" },
  { id: 152, name: "Reino Unido" },
  { id: 153, name: "República Centro-Africana" },
  { id: 154, name: "República Dominicana" },
  { id: 155, name: "República Tcheca" },
  { id: 156, name: "Romênia" },
  { id: 157, name: "Ruanda" },
  { id: 158, name: "Rússia" },
  { id: 159, name: "Samoa" },
  { id: 160, name: "San Marino" },
  { id: 161, name: "Santa Lúcia" },
  { id: 162, name: "São Cristóvão e Nevis" },
  { id: 163, name: "São Tomé e Príncipe" },
  { id: 164, name: "São Vicente e Granadinas" },
  { id: 165, name: "Seicheles" },
  { id: 166, name: "Senegal" },
  { id: 167, name: "Serra Leoa" },
  { id: 168, name: "Sérvia" },
  { id: 169, name: "Singapura" },
  { id: 170, name: "Síria" },
  { id: 171, name: "Somália" },
  { id: 172, name: "Sri Lanka" },
  { id: 173, name: "Sudão" },
  { id: 174, name: "Sudão do Sul" },
  { id: 175, name: "Suécia" },
  { id: 176, name: "Suíça" },
  { id: 177, name: "Suriname" },
  { id: 178, name: "Tailândia" },
  { id: 179, name: "Taiwan" },
  { id: 180, name: "Tajiquistão" },
  { id: 181, name: "Tanzânia" },
  { id: 182, name: "Timor-Leste" },
  { id: 183, name: "Togo" },
  { id: 184, name: "Tonga" },
  { id: 185, name: "Trinidad e Tobago" },
  { id: 186, name: "Tunísia" },
  { id: 187, name: "Turcomenistão" },
  { id: 188, name: "Turquia" },
  { id: 189, name: "Tuvalu" },
  { id: 190, name: "Ucrânia" },
  { id: 191, name: "Uganda" },
  { id: 192, name: "Uruguai" },
  { id: 193, name: "Uzbequistão" },
  { id: 194, name: "Vanuatu" },
  { id: 195, name: "Vaticano" },
  { id: 196, name: "Venezuela" },
  { id: 197, name: "Vietnã" },
  { id: 198, name: "Zâmbia" },
  { id: 199, name: "Zimbábue" }
];